name: Run PHP Script
on:
  push:
    branches:
      - main
jobs:
  php-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run PHP script
        run: php index.php
